name: CI Pipeline

on: [push] # Executa a cada push no repositório

jobs:
  test-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: echo "This job tests something"

  test-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Second Hello Step
        run: echo "This is the second test job"